#!/bin/bash

# Script para analizar APIs de Business Central disponibles vs utilizadas en n8n

echo "🔍 Análisis de APIs de Business Central"
echo "======================================"
echo ""

# APIs disponibles en Business Central (extraídas del proyecto)
echo "📋 APIs DISPONIBLES en Business Central:"
echo "----------------------------------------"

# APIs v2.0
echo "🔹 APIs v2.0:"
echo "  - PS_Proyectos (50206)"
echo "  - PS_Proyectos_Tareas (50222)"
echo "  - PS_Proyectos_Equipo (50223)"
echo "  - PS_Recursos (50207)"
echo "  - PS_Recursos_Costos (50224)"
echo "  - PS_Calendaro_Periodos_Dias (50225)"
echo "  - PS_HistoricoPlanificacionMes (50221)"
echo "  - PS_Years (50220)"
echo "  - PS_PlanificacionMes (50219)"
echo "  - PS_ObjectivesByDepartaments (50218)"
echo "  - PS_MesesCerrados (50217)"
echo "  - PS_ExpedienteMes (50215)"
echo "  - PS_MovimientosProyectosMes (50214)"
echo "  - PS_DiasDeImputacion (50212)"
echo "  - PS_PresentacionIva (50211)"
echo "  - PS_Links (50210)"
echo "  - PS_Tipologias (50209)"
echo "  - PS_Tecnologias (50208)"
echo "  - PS_MovimientosProyectos (50205)"
echo "  - PS_EquipoProyectos (50204)"
echo "  - PS_Departamentos (50203)"
echo "  - PS_ConfiguracionUsuarios (50202)"
echo "  - PS_ConceptosAnaliticos (50201)"
echo "  - PS_CentrosDeResponsabilidad (50200)"
echo "  - PS_TimeSheetLinesAPI (50736)"
echo ""

# APIs v1.0
echo "🔹 APIs v1.0:"
echo "  - PS_UpdateSeriesAPI (50737)"
echo "  - PS_InsertLine_API (50735)"
echo ""

# APIs de Pages
echo "🔹 APIs de Pages:"
echo "  - PS_TimesheetHeaderAPI (50734)"
echo ""

echo "📊 APIs UTILIZADAS en n8n:"
echo "-------------------------"

# APIs utilizadas en workflow 001
echo "🔹 Workflow 001_sincronizacion_completa_smart:"
echo "  ✅ PS_Proyectos_Tareas (job_task)"
echo "  ✅ PS_Recursos (resource)"
echo "  ✅ PS_Proyectos (job)"
echo "  ✅ PS_Proyectos_Equipo (job_team)"
echo "  ✅ PS_Recursos_Costos (resource_cost)"
echo "  ✅ PS_Calendaro_Periodos_Dias (calendar_period_days)"
echo ""

# APIs utilizadas en workflow 002
echo "🔹 Workflow 002_sync_supabase_to_bc_multi:"
echo "  ✅ PS_TimesheetHeaderAPI (resourcetimesheetheaders)"
echo "  ✅ PS_InsertLine_API (insertlines)"
echo ""

# APIs utilizadas en warmup
echo "🔹 Workflow 000_warmup_credentials:"
echo "  ✅ Companies (endpoint estándar BC)"
echo "  ✅ PS_Proyectos (solo para test)"
echo ""

echo "❌ APIs NO UTILIZADAS en n8n:"
echo "----------------------------"

# APIs no utilizadas
echo "🔸 APIs v2.0 no utilizadas:"
echo "  ❌ PS_HistoricoPlanificacionMes (50221)"
echo "  ❌ PS_Years (50220)"
echo "  ❌ PS_PlanificacionMes (50219)"
echo "  ❌ PS_ObjectivesByDepartaments (50218)"
echo "  ❌ PS_MesesCerrados (50217)"
echo "  ❌ PS_ExpedienteMes (50215)"
echo "  ❌ PS_MovimientosProyectosMes (50214)"
echo "  ❌ PS_DiasDeImputacion (50212)"
echo "  ❌ PS_PresentacionIva (50211)"
echo "  ❌ PS_Links (50210)"
echo "  ❌ PS_Tipologias (50209)"
echo "  ❌ PS_Tecnologias (50208)"
echo "  ❌ PS_MovimientosProyectos (50205)"
echo "  ❌ PS_EquipoProyectos (50204)"
echo "  ❌ PS_Departamentos (50203)"
echo "  ❌ PS_ConfiguracionUsuarios (50202)"
echo "  ❌ PS_ConceptosAnaliticos (50201)"
echo "  ❌ PS_CentrosDeResponsabilidad (50200)"
echo "  ❌ PS_TimeSheetLinesAPI (50736)"
echo ""

echo "🔸 APIs v1.0 no utilizadas:"
echo "  ❌ PS_UpdateSeriesAPI (50737)"
echo ""

echo "📈 RESUMEN:"
echo "----------"
echo "Total APIs disponibles: 28"
echo "APIs utilizadas en n8n: 8"
echo "APIs no utilizadas: 20"
echo "Porcentaje de uso: 28.6%"
echo ""

echo "💡 RECOMENDACIONES:"
echo "------------------"
echo "1. ✅ Mantener APIs utilizadas en n8n (8 APIs)"
echo "2. ❌ Considerar eliminar APIs no utilizadas (20 APIs)"
echo "3. 🔍 Revisar si alguna API no utilizada es necesaria para funcionalidad futura"
echo "4. 📝 Documentar APIs eliminadas para referencia futura"
echo ""

echo "🗑️  APIs CANDIDATAS PARA ELIMINACIÓN:"
echo "------------------------------------"
echo "Las siguientes APIs pueden ser eliminadas del proyecto BC:"
echo ""
echo "Queries v2.0 (20 APIs):"
echo "  - PS_HistoricoPlanificacionMes"
echo "  - PS_Years"
echo "  - PS_PlanificacionMes"
echo "  - PS_ObjectivesByDepartaments"
echo "  - PS_MesesCerrados"
echo "  - PS_ExpedienteMes"
echo "  - PS_MovimientosProyectosMes"
echo "  - PS_DiasDeImputacion"
echo "  - PS_PresentacionIva"
echo "  - PS_Links"
echo "  - PS_Tipologias"
echo "  - PS_Tecnologias"
echo "  - PS_MovimientosProyectos"
echo "  - PS_EquipoProyectos"
echo "  - PS_Departamentos"
echo "  - PS_ConfiguracionUsuarios"
echo "  - PS_ConceptosAnaliticos"
echo "  - PS_CentrosDeResponsabilidad"
echo "  - PS_TimeSheetLinesAPI"
echo ""
echo "Pages v1.0 (1 API):"
echo "  - PS_UpdateSeriesAPI"
echo ""
echo "Total: 21 APIs pueden ser eliminadas"
