#!/bin/bash

# Script final para configurar la conexión a Supabase
# Uso: ./scripts/final-setup.sh

echo "🎯 CONFIGURACIÓN FINAL DE METABASE CON SUPABASE"
echo "================================================"
echo ""
echo "✅ Metabase está funcionando correctamente"
echo "✅ Conectividad a Supabase resuelta (IPv4)"
echo "✅ Contraseña de Supabase obtenida"
echo ""
echo "📋 PASOS PARA COMPLETAR LA CONFIGURACIÓN:"
echo ""
echo "1. 🌐 ACCEDE A METABASE:"
echo "   URL: http://192.168.88.68:3000"
echo ""
echo "2. 👤 INICIA SESIÓN:"
echo "   Usa las credenciales que configuraste anteriormente"
echo ""
echo "3. 🗄️ CONFIGURA LA BASE DE DATOS:"
echo "   - Ve a Settings > Admin > Databases"
echo "   - Haz clic en 'Add database'"
echo "   - Selecciona 'PostgreSQL'"
echo ""
echo "4. 📝 DATOS DE CONEXIÓN A SUPABASE:"
echo "   ┌─────────────────────────────────────────────────────────┐"
echo "   │ Name: Supabase Timesheet                                │"
echo "   │ Host: db.qfpswxjunoepznrpsltt.supabase.co              │"
echo "   │ Port: 5432                                             │"
echo "   │ Database name: postgres                                │"
echo "   │ Username: postgres                                     │"
echo "   │ Password: e3u2zDnt4mGMJFWA                            │"
echo "   │ SSL Mode: require                                      │"
echo "   └─────────────────────────────────────────────────────────┘"
echo ""
echo "5. ✅ VERIFICAR CONEXIÓN:"
echo "   - Haz clic en 'Test connection'"
echo "   - Debería mostrar 'Successfully connected'"
echo "   - Haz clic en 'Save'"
echo ""
echo "📊 TABLAS DISPONIBLES UNA VEZ CONECTADO:"
echo "   • job - Proyectos"
echo "   • job_task - Tareas de proyectos"
echo "   • job_team - Equipos asignados a proyectos"
echo "   • resource - Recursos/Empleados"
echo "   • resource_cost - Costos de recursos"
echo "   • calendar_period_days - Días de calendario"
echo "   • timesheet - Líneas de timesheet"
echo "   • resource_timesheet_header - Cabeceras de timesheet"
echo ""
echo "🎉 ¡UNA VEZ CONFIGURADO PODRÁS:"
echo "   • Crear dashboards automáticos"
echo "   • Hacer consultas SQL"
echo "   • Visualizar datos de tu aplicación timesheet"
echo "   • Crear alertas y notificaciones"
echo ""
echo "🔧 COMANDOS DE GESTIÓN:"
echo "   • Ver estado: docker compose ps"
echo "   • Ver logs: docker compose logs -f metabase"
echo "   • Parar: ./scripts/stop.sh"
echo "   • Iniciar: ./scripts/start.sh"
echo ""
echo "📞 Si tienes problemas, revisa los logs con:"
echo "   ssh root@192.168.88.68 'cd /opt/metabase-docker && docker compose logs metabase'"








