services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: timesheet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - timesheet-network

  # Supabase Studio (Dashboard) - Comentado temporalmente por problemas de versión
  # studio:
  #   image: supabase/studio:latest
  #   container_name: timesheet-studio
  #   restart: unless-stopped
  #   environment:
  #     SUPABASE_URL: http://kong:8000
  #     SUPABASE_REST_URL: http://kong:8000/rest/v1/
  #     SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcHN3eGp1bm9lcHpucnBzbHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzEwNzksImV4cCI6MjA2OTQ0NzA3OX0.d78PxMnKsipdse_ozBSwTrEMs354rIvayh4lXE1LMW4
  #     SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcHN3eGp1bm9lcHpucnBzbHR0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Mzg3MTA3OSwiZXhwIjoyMDY5NDQ3MDc5fQ.PxpfuFsfvpeEPHCEiWhRn0SD1WxngTAEppJ-65QTTOQ
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - kong
  #   networks:
  #     - timesheet-network

  # Kong API Gateway
  kong:
    image: kong:2.8.1
    container_name: timesheet-kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ./kong-simple.yml:/var/lib/kong/kong.yml:ro
    networks:
      - timesheet-network

  # Auth Service
  auth:
    image: supabase/gotrue:v2.158.1
    container_name: timesheet-auth
    restart: unless-stopped
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: "*"
      GOTRUE_DISABLE_SIGNUP: false
      GOTRUE_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_EXTERNAL_EMAIL_ENABLED: true
      GOTRUE_MAILER_AUTOCONFIRM: true
      GOTRUE_SMTP_ADMIN_EMAIL: admin@example.com
      GOTRUE_SMTP_HOST: localhost
      GOTRUE_SMTP_PORT: 1025
      GOTRUE_SMTP_USER: fake_mail_user
      GOTRUE_SMTP_PASS: fake_mail_password
      GOTRUE_SMTP_SENDER_NAME: fake_sender
    ports:
      - "9999:9999"
    depends_on:
      - postgres
    networks:
      - timesheet-network

  # REST API
  rest:
    image: postgrest/postgrest:v12.2.0
    container_name: timesheet-rest
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/postgres
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
      PGRST_DB_USE_LEGACY_GUCS: "false"
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    networks:
      - timesheet-network

  # Realtime
  realtime:
    image: supabase/realtime:v2.30.8
    container_name: timesheet-realtime
    restart: unless-stopped
    environment:
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime'
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
      FLY_ALLOC_ID: fly123
      FLY_APP_NAME: realtime
      SECRET_KEY_BASE: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
    depends_on:
      - postgres
    networks:
      - timesheet-network

  # Storage
  storage:
    image: supabase/storage-api:v1.10.1
    container_name: timesheet-storage
    restart: unless-stopped
    environment:
      ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzU4Nzg0Mzk1LCJleHAiOjE5MTY0NjQzOTV9.O5zhmVObajk-c5HAcgtlt02l2x_Jhg_MU6b4MKN8jOo
      SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE3NTg3ODQzOTUsImV4cCI6MTkxNjQ2NDM5NX0.CF7khUW5nicbMIeoACR-h1yF4O743oiFC0_DLOGsmi8
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: stub
      GLOBAL_S3_BUCKET: stub
    ports:
      - "5000:5000"
    volumes:
      - storage_data:/var/lib/storage
    depends_on:
      - postgres
      - rest
    networks:
      - timesheet-network

  # Edge Functions
  functions:
    image: supabase/edge-runtime:v1.58.0
    container_name: timesheet-functions
    restart: unless-stopped
    environment:
      JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzU4Nzg0Mzk1LCJleHAiOjE5MTY0NjQzOTV9.O5zhmVObajk-c5HAcgtlt02l2x_Jhg_MU6b4MKN8jOo
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE3NTg3ODQzOTUsImV4cCI6MTkxNjQ2NDM5NX0.CF7khUW5nicbMIeoACR-h1yF4O743oiFC0_DLOGsmi8
    ports:
      - "9000:9000"
    volumes:
      - ./functions:/home/deno/functions:ro
    depends_on:
      - kong
    networks:
      - timesheet-network

volumes:
  postgres_data:
  storage_data:

networks:
  timesheet-network:
    driver: bridge
